#!/usr/bin/env perl
use Dzpl
    name => 'App-PAUSE-cleanup',
    version => '0.0010',
    author => 'Robert Krimen <robertkrimen@gmail.com>',
    license => 'Perl5',
    copyright => 'Robert Krimen',

    require => q/
        [Test]
        Test::Most
    /,
;

{ plugin '@ROKR' }

